title: Gianni Gambetti
author: Gianni Gambetti
exclude: [ 'Makefile', '.gitignore', 'Tupfile', '.gitmodules' ]
lastupdate: '2015/11/15'
navigation: [
    {'name': 'About', 'path':'about' }
    ,{'name': 'Blog', 'path':'blog' }
    ,{'name': 'Contact', 'path':'contact' }
    ,{'name': 'Resume', 'path':'resume' } ]


baseurl: //volatiledream.github.io
markdown: kramdown
