title: Gianni Gambetti
author: Gianni Gambetti
exclude: [ 'Makefile', '.gitignore' ]
motto: { 'text': 'non sum qualis eram', 'lang': 'lat', 'link': 'http://translate.google.com/?hl=en&tab=wT#la/en/non%20sum%20qualis%20eram'}
lastupdate: '2013-06-25'
navigation: [
	{'name': 'About', 'icon': 'user', 'path':'about' }
	,{'name': 'Blog', 'icon': 'list', 'path':'blog' }
	,{'name': 'Contact', 'icon': 'envelope', 'path':'contact' }
	,{'name': 'Resume', 'icon': 'file', 'path':'resume' } ]
baseurl: http://volatiledream.github.io
