title: Gianni Gambetti
author: Gianni Gambetti
exclude: [ 'Makefile', '.gitignore', 'Tupfile', '.gitmodules' ]
navigation: [
    {'name': 'About', 'path':'about' }
    ,{'name': 'Blog', 'path':'blog' }
    ,{'name': 'Contact', 'path':'contact' }
    ,{'name': 'Resume', 'path':'resume' } ]


markdown: kramdown
